version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    environment:
      MONGO_URI: "mongodb+srv://rohit1osc:0VuPaBi3Ti4MMChd@cluster0.fgmzs.mongodb.net/"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
